// Package runtime embeds the C runtime that ships with the compiler.
package runtime

import _ "embed"

// Header is tyrt.h.
//
//go:embed src/tyrt.h
var Header string

// PlatHeader is tyrt_plat.h: the platform layer's interface. Every operating
// system call the runtime makes is declared there, and the runtime's own files
// call those declarations rather than the calls themselves, so the runtime has
// one file to port rather than one per file.
//
//go:embed src/tyrt_plat.h
var PlatHeader string

// Core is tyrt.c.
//
//go:embed src/tyrt.c
var Core string

// Extra is tyrt2.c.
//
//go:embed src/tyrt2.c
var Extra string

// Net is tyrt_net.c: the socket and file-descriptor primitives. It is a file of
// its own so that the networking code does not have to be read past to find the
// allocator, and so that a program that never opens a socket still links one
// translation unit it does not call.
//
//go:embed src/tyrt_net.c
var Net string

// Reflect is tyrt_reflect.c: class metadata access, the field and method
// tables, and reflective invocation. It is a file of its own for the same
// reason as Net: a program that never reflects should not have to link the
// invoker thunks' callee, and a reader looking for java.lang.reflect's
// behaviour should not have to read past the allocator to find it.
//
//go:embed src/tyrt_reflect.c
var Reflect string

// Thread is tyrt_thread.c: the per-thread runtime state, the thread registry,
// the stop-the-world protocol a collection runs the other threads through, and
// the monitors `synchronized` and Object.wait are built on. It is a file of its
// own because it is the one part of the runtime that is about more than one
// thread at a time: a program that never starts a thread still links it (the
// main thread is a thread), but a reader looking for the allocator or for
// java.lang has no reason to read past it.
//
//go:embed src/tyrt_thread.c
var Thread string

// TLS is tyrt_tls.c: TLS over the socket layer, built on OpenSSL. It is a file
// of its own because it is the one part of the runtime that links a library the
// compiler does not ship: the build compiles it, and passes -lssl -lcrypto,
// only for a program whose reachable code calls one of its helpers, so that
// every program that does not use TLS stays a binary that needs nothing but the
// C library (see internal/codegen/prune.go and internal/driver/driver.go).
//
//go:embed src/tyrt_tls.c
var TLS string

// Unicode is tyrt_unicode.c: the classification and case mapping tables of
// Unicode 15.0.0, generated by internal/tools/genunicode from the data files
// that sit beside it. It is a file of its own because it is data and not code --
// three hundred kilobytes that a reader of the runtime has no reason to read
// past, and that `make unicode-tables` rewrites whole -- and because the linker
// can then drop it from a program that reaches none of the helpers that read it.
//
//go:embed src/tyrt_unicode.c
var Unicode string

// PlatPosix and PlatWin are tyrt_plat.h's two implementations: the POSIX one
// (the C library's threads, sockets and files) and the Windows one (winpthreads
// and Winsock). A build compiles exactly one of them, chosen by the target it
// was asked for, and which one that is happens in internal/driver. They are
// embedded both of them because a compiler that can build for Windows has to
// carry the Windows half of its runtime wherever it runs.
//
//go:embed src/tyrt_plat_posix.c
var PlatPosix string

//go:embed src/tyrt_plat_win.c
var PlatWin string
