package main

import (
	"fmt"
	"math/rand/v2"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/teyru-lang/Teyru/internal/driver"
)

// A dialect is one of the two spellings of the same language. They differ in
// punctuation and in nothing else, which is what makes a differential over them
// worth anything: Teyru writes `for (a : b : c)` where Java writes
// `for (a; b; c)`, and a statement ends at a newline here and at a semicolon
// there.
type dialect struct {
	name string
}

var (
	teyru = dialect{name: "teyru"}
	java  = dialect{name: "java"}
)

// A chunk is one statement of a generated program, in both spellings. The key
// is the label the statement prints, and it is fixed when the statement is
// generated, so deleting other statements does not renumber the output and the
// minimiser can compare two runs line by line.
type chunk struct {
	kind  string
	key   string
	teyru string
	java  string
}

func (c chunk) text(d dialect) string {
	if d.name == "teyru" {
		return c.teyru
	}
	return c.java
}

// A program is a class with a main whose statements are the chunks, plus the
// classes the virtual-call statements dispatch on.
type program struct {
	cls    string
	chunks []chunk
}

func (p *program) withOut(i int) *program {
	out := &program{cls: p.cls}
	out.chunks = append(out.chunks, p.chunks[:i]...)
	out.chunks = append(out.chunks, p.chunks[i+1:]...)
	return out
}

// kind is the construct a printed line came from, for the summary.
func (p *program) kind(key string) string {
	for _, c := range p.chunks {
		if c.key == key {
			return c.kind
		}
	}
	return "unknown (" + key + ")"
}

// render writes the program out in one dialect.
func (p *program) render(d dialect) string {
	semi := ""
	if d.name == "java" {
		semi = ";"
	}
	var b strings.Builder
	b.WriteString("// Generated by internal/tools/progen: the same program in both\n")
	b.WriteString("// spellings, so that two implementations of it can be compared.\n")
	if d.name == "teyru" {
		b.WriteString("import teyru.*\n\n")
	} else {
		b.WriteString("import java.util.*;\n\n")
	}
	// The classes the virtual-call statements dispatch on. They are always
	// here, so a program that lost every one of those statements still
	// compiles.
	fmt.Fprintf(&b, "class Base {\n  int v(int x) { return x + 1%s }\n  String name() { return \"base\"%s }\n}\n\n", semi, semi)
	fmt.Fprintf(&b, "class Derived extends Base {\n  int v(int x) { return x * 2%s }\n  String name() { return \"derived\"%s }\n}\n\n", semi, semi)
	fmt.Fprintf(&b, "class %s {\n", p.cls)
	fmt.Fprintf(&b, "  static String describe(Object o) { return \"o=\" + o%s }\n\n", semi)
	b.WriteString("  public static void main(String[] args) {\n")
	for _, c := range p.chunks {
		b.WriteString(c.text(d))
	}
	b.WriteString("  }\n}\n")
	return b.String()
}

// ---------------------------------------------------------------- generator

type gen struct {
	rng *rand.Rand
	n   int
	out []chunk
}

func generate(seed int, cls string, skip map[string]bool) *program {
	if cls == "" {
		cls = "Prog"
	}
	g := &gen{rng: rand.New(rand.NewPCG(uint64(seed)+1, uint64(seed)*2654435761+1))}
	// The order below is the order of the generated program, and it is the same
	// for every seed: the shapes are fixed and the values are the seed's, so a
	// difference that shows up at seed 137 is one combination of constructs
	// rather than a mystery.
	for _, fn := range []func(*gen){
		(*gen).intArithmetic,
		(*gen).intWrap,
		(*gen).longArithmetic,
		(*gen).doubleArithmetic,
		(*gen).conversions,
		(*gen).charArithmetic,
		(*gen).stringLength,
		(*gen).stringIndex,
		(*gen).stringCase,
		(*gen).stringFormat,
		(*gen).stringConcat,
		(*gen).arraySum,
		(*gen).arrayIndex,
		(*gen).loopSum,
		(*gen).whileLoop,
		(*gen).switchInt,
		(*gen).switchString,
		(*gen).tryDivide,
		(*gen).tryParse,
		(*gen).tryBounds,
		(*gen).virtualCall,
		(*gen).interfaceCall,
		(*gen).boxedIdentity,
		(*gen).boxedArithmetic,
		(*gen).listToString,
		(*gen).mathEdges,
	} {
		fn(g)
	}
	// A statement whose construct is already known to differ can be left out,
	// which is what makes this a search for differences nobody has found yet
	// rather than a re-run of the ones that are documented.
	out := g.out
	if len(skip) > 0 {
		out = nil
		for _, c := range g.out {
			if !skip[c.kind] {
				out = append(out, c)
			}
		}
	}
	return &program{cls: cls, chunks: out}
}

// keyMarker stands where the statement's printed label goes, so that the label
// is decided by the generator rather than by the call site.
const keyMarker = "@"

// forSep stands where a classic for-header's separator goes: Teyru writes `:`
// there and Java `;`, and an enhanced for's colon is written out as itself.
const forSep = "|SEP|"

// add records a statement, written once in Teyru's spelling. Java's is the same
// text with a semicolon at the end of every statement and a `;` in every
// classic for-header: those are the only two differences this subset has.
func (g *gen) add(kind, format string, args ...any) {
	g.n++
	key := fmt.Sprintf("k%d", g.n)
	text := fmt.Sprintf(strings.ReplaceAll(format, keyMarker, key), args...)
	g.out = append(g.out, chunk{
		kind:  kind,
		key:   key,
		teyru: fmt.Sprintf("    %s\n", strings.ReplaceAll(text, forSep, ":")),
		java:  fmt.Sprintf("    %s\n", punctuate(strings.ReplaceAll(text, forSep, ";"))),
	})
}

// punctuate turns one Teyru statement into the Java one: every line that is not
// a brace, a case label or empty gets the semicolon Java ends it with.
func punctuate(s string) string {
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case trimmed == "",
			strings.HasSuffix(trimmed, ";"),
			strings.HasSuffix(trimmed, "{"),
			strings.HasSuffix(trimmed, ":"),
			// a line that *is* a closing brace ends a block; a line that
			// merely ends with one is an array initialiser, and is a statement
			strings.HasPrefix(trimmed, "}"):
		default:
			lines[i] = line + ";"
		}
	}
	return strings.Join(lines, "\n")
}

func (g *gen) intn(n int) int           { return g.rng.IntN(n) }
func (g *gen) pick(xs ...string) string { return xs[g.rng.IntN(len(xs))] }

func (g *gen) intArithmetic() {
	a := g.intn(200) - 100
	b := g.intn(20) - 10
	if b == 0 {
		b = 3
	}
	g.add("int arithmetic",
		"int v1 = %d %s %d\nSystem.out.println(\"@ = \" + v1)",
		a, g.pick("+", "-", "*", "/", "%", "<<", ">>", "&", "|", "^"), b)
}

func (g *gen) intWrap() {
	g.add("int overflow",
		"int v2 = 2147483647 + %d\nSystem.out.println(\"@ = \" + v2)",
		g.intn(1000))
}

func (g *gen) longArithmetic() {
	a := int64(g.intn(1<<40)) - (1 << 39)
	b := int64(g.intn(1000)) + 1
	g.add("long arithmetic",
		"long v3 = %dL %s %dL\nSystem.out.println(\"@ = \" + v3)",
		a, g.pick("+", "-", "*", "/", "%"), b)
}

func (g *gen) doubleArithmetic() {
	a := float64(g.intn(1000)) / float64(g.intn(7)+1)
	b := float64(g.intn(100))/4 + 1
	g.add("double arithmetic",
		"double v4 = %s %s %s\nSystem.out.println(\"@ = \" + v4)",
		formatDouble(a), g.pick("+", "-", "*", "/"), formatDouble(b))
}

func (g *gen) conversions() {
	g.add("narrowing conversion",
		"byte v5 = (byte) %d\nshort v6 = (short) %d\nint v7 = (int) %dL\n"+
			"System.out.println(\"@ = \" + v5 + \",\" + v6 + \",\" + v7)",
		g.intn(300)-150, g.intn(80000)-40000, int64(g.intn(1<<40))-(1<<39))
}

func (g *gen) charArithmetic() {
	g.add("char arithmetic",
		"char v8 = '%c'\nv8 += %d\nSystem.out.println(\"@ = \" + (int) v8 + \",\" + v8 + \",\" + (char) (v8 + 2))",
		rune('a'+g.intn(26)), g.intn(10)+1)
}

func (g *gen) stringLength() {
	g.add("string length",
		"String v9 = \"%s\"\nSystem.out.println(\"@ = \" + v9.length() + \",\" + v9.charAt(0))",
		g.pick("中文", "😀", "a中b", "héllo", "ab"))
}

func (g *gen) stringIndex() {
	s := g.pick("中文中文", "a😀b", "abc中", "日本語")
	g.add("string index",
		"String v10 = \"%s\"\nSystem.out.println(\"@ = \" + v10.indexOf(\"中\") + \",\" + v10.lastIndexOf(\"中\") + \",\" + v10.substring(0, 1))",
		s)
}

func (g *gen) stringCase() {
	g.add("case mapping",
		"String v11 = \"%s\"\nSystem.out.println(\"@ = \" + v11.toUpperCase() + \",\" + v11.toLowerCase())",
		g.pick("ß", "ΟΔΟΣ", "İ", "abc", "中文"))
}

func (g *gen) stringFormat() {
	s := g.pick("中", "ab中", "😀", "x")
	n := g.intn(8) + 2
	g.add("String.format",
		"System.out.println(\"@ = [\" + String.format(\"%%%ds|%%-%ds\", \"%s\", \"%s\") + \"]\")",
		n, n, s, s)
}

func (g *gen) stringConcat() {
	g.add("string concatenation",
		"System.out.println(\"@ = \" + (%d + \"\" + '%c') + \",\" + (\"\" + '%c' + %d))",
		g.intn(100)-50, rune('A'+g.intn(26)), rune('A'+g.intn(26)), g.intn(100)-50)
}

func (g *gen) arraySum() {
	n := g.intn(4) + 2
	vals := make([]string, n)
	for i := range vals {
		vals[i] = fmt.Sprint(g.intn(50) - 25)
	}
	g.add("array sum",
		"int[] v12 = new int[] {%s}\nint v13 = 0\nfor (int x : v12) {\nv13 += x\n}\n"+
			"System.out.println(\"@ = \" + v12.length + \",\" + v13 + \",\" + v12[0])",
		strings.Join(vals, ", "))
}

func (g *gen) arrayIndex() {
	g.add("array indexing",
		"int[] v14 = new int[3]\nfor (int i = 0 "+forSep+" i < v14.length "+forSep+" i++) {\nv14[i] = i * %d\n}\n"+
			"System.out.println(\"@ = \" + v14[0] + \",\" + v14[1] + \",\" + v14[2])",
		g.intn(5)+1)
}

func (g *gen) loopSum() {
	g.add("for loop",
		"int v15 = 0\nfor (int i = 0 "+forSep+" i < %d "+forSep+" i = i + %d) {\nv15 = v15 * 2 + i\n}\n"+
			"System.out.println(\"@ = \" + v15)",
		g.intn(10)+1, g.intn(3)+1)
}

func (g *gen) whileLoop() {
	g.add("while loop",
		"int v16 = %d\nint v17 = 0\nwhile (v16 > 0) {\nv17 += v16\nv16--\n}\n"+
			"System.out.println(\"@ = \" + v17)",
		g.intn(6)+1)
}

func (g *gen) switchInt() {
	g.add("switch on int",
		"int v18 = %d\nswitch (v18) {\ncase 0:\nSystem.out.println(\"@ = zero\")\nbreak\n"+
			"case 1:\nSystem.out.println(\"@ = one\")\nbreak\ndefault:\nSystem.out.println(\"@ = other \" + v18)\n}",
		g.intn(5))
}

func (g *gen) switchString() {
	g.add("switch on string",
		"String v19 = \"%s\"\nswitch (v19) {\ncase \"你好\":\nSystem.out.println(\"@ = nl\")\nbreak\n"+
			"case \"中\":\nSystem.out.println(\"@ = zh\")\nbreak\ndefault:\nSystem.out.println(\"@ = other\")\n}",
		g.pick("你好", "中", "hello"))
}

func (g *gen) tryDivide() {
	g.add("division by zero caught",
		"try {\nint v20 = %d / %d\nSystem.out.println(\"@ = \" + v20)\n} catch (ArithmeticException e) {\nSystem.out.println(\"@ = caught \" + e.getMessage())\n}",
		g.intn(100)-50, g.intn(4)-2)
}

func (g *gen) tryParse() {
	g.add("NumberFormatException caught",
		"try {\nint v21 = Integer.parseInt(\"%s\")\nSystem.out.println(\"@ = \" + v21)\n} catch (NumberFormatException e) {\nSystem.out.println(\"@ = caught \" + e.getMessage())\n}",
		g.pick("12", "abc", " 5", "+5", "999999999999"))
}

func (g *gen) tryBounds() {
	g.add("array bounds caught",
		"try {\nint[] v22 = new int[%d]\nv22[%d] = 1\nSystem.out.println(\"@ = \" + v22.length)\n} catch (ArrayIndexOutOfBoundsException e) {\nSystem.out.println(\"@ = caught \" + e.getMessage())\n}",
		g.intn(3)+1, g.intn(10)+3)
}

func (g *gen) virtualCall() {
	k := g.intn(50)
	g.add("virtual call",
		"Base v23 = new Derived()\nBase v24 = new Base()\n"+
			"System.out.println(\"@ = \" + v23.v(%d) + \",\" + v24.v(%d) + \",\" + v23.name() + \",\" + v24.name())",
		k, k)
}

func (g *gen) interfaceCall() {
	k := g.intn(30)
	g.add("boxed call through an interface value",
		"Comparable<Integer> v25 = Integer.valueOf(%d)\n"+
			"System.out.println(\"@ = \" + v25.compareTo(Integer.valueOf(%d)) + \",\" + describe(v25))",
		k, g.intn(30))
}

func (g *gen) boxedIdentity() {
	k := g.intn(300) - 20
	g.add("boxed identity",
		"Integer v26 = %d\nInteger v27 = %d\n"+
			"System.out.println(\"@ = \" + (v26 == v27) + \",\" + v26.equals(v27))",
		k, k)
}

func (g *gen) boxedArithmetic() {
	k := g.intn(1000)
	g.add("boxed arithmetic",
		"Integer v28 = %d\nint v29 = v28 + %d\nLong v30 = %dL\n"+
			"System.out.println(\"@ = \" + v29 + \",\" + v30 + \",\" + (v30 + 1))",
		k, g.intn(50), k)
}

func (g *gen) listToString() {
	n := g.intn(3) + 1
	vals := make([]string, n)
	for i := range vals {
		vals[i] = fmt.Sprint(g.intn(20))
	}
	g.add("collection toString",
		"ArrayList<Integer> v31 = new ArrayList<Integer>()\nfor (int x : new int[] {%s}) {\nv31.add(x)\n}\n"+
			"TreeSet<Integer> v32 = new TreeSet<Integer>(v31)\n"+
			"System.out.println(\"@ = \" + v31 + \",\" + v32 + \",\" + Arrays.toString(new int[] {%s}))",
		strings.Join(vals, ", "), strings.Join(vals, ", "))
}

func (g *gen) mathEdges() {
	g.add("Math edges",
		"System.out.println(\"@ = \" + Math.abs(%d) + \",\" + Math.round(%s) + \",\" + Math.min(%d, %d) + \",\" + Double.compare(-0.0, 0.0))",
		g.intn(100)-100, formatDouble(float64(g.intn(1000))/8), g.intn(50)-25, g.intn(50)-25)
}

// ---------------------------------------------------------------- formatting

func formatDouble(f float64) string {
	s := fmt.Sprintf("%g", f)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// ---------------------------------------------------------------- running

type result struct {
	teyruOut  string
	javaOut   string
	teyruCode int
	javaCode  int
	err       error
}

func (r result) same() bool { return r.teyruOut == r.javaOut && r.teyruCode == r.javaCode }

// differingKeys lists the printed labels whose lines differ, so that the
// summary can say which construct the difference came from.
func (r result) differingKeys() []string {
	t := strings.Split(r.teyruOut, "\n")
	j := strings.Split(r.javaOut, "\n")
	var out []string
	for i := 0; i < len(t) || i < len(j); i++ {
		var a, b string
		if i < len(t) {
			a = t[i]
		}
		if i < len(j) {
			b = j[i]
		}
		if a == b {
			continue
		}
		out = append(out, label(a, b))
	}
	return out
}

// label is the printed key of a line, which is what it says before " = ".
func label(lines ...string) string {
	for _, line := range lines {
		if i := strings.Index(line, " = "); i > 0 {
			return line[:i]
		}
	}
	return strings.TrimSpace(strings.Join(lines, " / "))
}

func (r result) report() string {
	var b strings.Builder
	fmt.Fprintf(&b, "--- teyru (exit %d)\n%s", r.teyruCode, r.teyruOut)
	fmt.Fprintf(&b, "--- java (exit %d)\n%s", r.javaCode, r.javaOut)
	return b.String()
}

// A runner compiles and runs a program with both implementations.
type runner struct {
	javac  string
	java   string
	keep   bool
	serial int
}

func (r *runner) run(p *program) result {
	r.serial++
	dir, err := os.MkdirTemp("", fmt.Sprintf("progen-%d-", r.serial))
	if err != nil {
		return result{err: err}
	}
	if !r.keep {
		defer os.RemoveAll(dir)
	}
	tsrc := filepath.Join(dir, p.cls+".teyru")
	jsrc := filepath.Join(dir, p.cls+".java")
	if err := os.WriteFile(tsrc, []byte(p.render(teyru)), 0o644); err != nil {
		return result{err: err}
	}
	if err := os.WriteFile(jsrc, []byte(p.render(java)), 0o644); err != nil {
		return result{err: err}
	}
	res := result{}
	exe := filepath.Join(dir, "prog")
	build, err := driver.Compile([]string{tsrc}, driver.Options{Out: exe, Opt: "-O1"})
	if err != nil {
		diags := ""
		if build != nil && build.Diags != nil {
			diags = build.Diags.String()
		}
		res.err = fmt.Errorf("teyru refused the generated program: %v\n%s", err, diags)
		return res
	}
	res.teyruOut, res.teyruCode = runCmd(exe)
	classes := filepath.Join(dir, "classes")
	if err := os.MkdirAll(classes, 0o755); err != nil {
		res.err = err
		return res
	}
	if out, err := exec.Command(r.javac, "-nowarn", "-d", classes, jsrc).CombinedOutput(); err != nil {
		res.err = fmt.Errorf("javac refused the generated program: %v\n%s", err, out)
		return res
	}
	res.javaOut, res.javaCode = runCmd(r.java, "-ea", "-Dstdout.encoding=UTF-8",
		"-Duser.language=en", "-Duser.country=US", "-cp", classes, p.cls)
	return res
}

func runCmd(name string, args ...string) (string, int) {
	cmd := exec.Command(name, args...)
	out, err := cmd.Output()
	if err == nil {
		return string(out), 0
	}
	if ee, ok := err.(*exec.ExitError); ok {
		return string(out), ee.ExitCode()
	}
	return string(out), -1
}
